apiVersion: v1
kind: Secret
metadata:
  name: {{ include "anna.fullname" . }}
  labels:
    {{- include "anna.labels" . | nindent 4 }}
type: Opaque
data:
  openai-api-key: {{ .Values.secret.openaiApiKey | b64enc | quote }}
  sentry-dsn: {{ .Values.secret.sentryDsn | b64enc | quote }}
  twilio-account-sid: {{ .Values.secret.twilioAccountSid | b64enc | quote }}
  twilio-auth-token: {{ .Values.secret.twilioAuthToken | b64enc | quote }}
  twilio-phone-number: {{ .Values.secret.twilioPhoneNumber | b64enc | quote }}
  fhir-server-url: {{ .Values.secret.fhirServerUrl | b64enc | quote }}
  redis-url: {{ .Values.secret.redisUrl | b64enc | quote }}
  django-secret-key: {{ .Values.secret.djangoSecretKey | b64enc | quote }}