replicaCount: 1

image:
  repository: anna
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: anna.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: anna-tls
      hosts:
        - anna.example.com

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

# ANNA specific configuration
redis:
  enabled: true
  host: redis
  port: 6379
  db: 0

# Secret values to be provided via Secret
# These will be referenced in Secret template
secret:
  openaiApiKey: ""
  sentryDsn: ""
  twilioAccountSid: ""
  twilioAuthToken: ""
  twilioPhoneNumber: ""
  fhirServerUrl: ""
  redisUrl: ""
  djangoSecretKey: ""